name: 'Pull Request Conflict Finder'
description: 'Check pull requests for conflicts and label them'
inputs:
  secret_token:
    description: 'Github secret token'
    required: true
  conflict_label:
    description: 'Label to be used for PRs with conflicts'
    required: true
    default: 'Has Conflict'
  max_tries:
    description: 'Number of times the action should try to get the merge status'
    required: true
    default: "5"
  wait_ms:
    description: 'Number of millisecconds the action should wait between tries'
    required: true
    default: "5000"
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'alert-octagon'
  color: 'red'
